import { Router } from "express";
import * as categoryController from "./subcategory.controller.js";
import fileUpload, { fileType } from '../../utls/multer.js';
import { auth } from '../../middelware/auth.js';
const router = Router({mergeParams: true});
router.post('/' ,auth(['Admin']) ,fileUpload(fileType.image).single('image'),categoryController.create);
router.get('/',categoryController.getAll);
router.get('/active' ,auth(), categoryController.getActive);
router.get('/:id',categoryController.getDetails);
router.patch('/:id',auth() ,fileUpload(fileType.image).single('image'),categoryController.update);
router.delete('/:id',auth() ,categoryController.destory);
export default router;