import { Router } from "express";
import * as categoryController from "./category.controller.js";
import fileUpload, { fileType } from './../../utls/multer.js';
import { auth ,roles } from '../../middelware/auth.js';
import subcategoryRouter from './../subcategory/subcategory.router.js';
import {endPoints} from '../category/category.role.js';
const router = Router();
router.use('/:id/subcategory',subcategoryRouter);
router.post('/' ,auth(endPoints.create) ,fileUpload(fileType.image).single('image'),categoryController.create);
router.get('/',auth(endPoints.get) ,categoryController.getAll);
router.get('/active' ,auth(endPoints.getActive) , categoryController.getActive);
router.get('/:id',auth(endPoints.getActive) ,categoryController.getDetails);
router.patch('/:id',auth(endPoints.create) ,fileUpload(fileType.image).single('image'),categoryController.update);
router.delete('/:id',auth(endPoints.delete) ,categoryController.destory);
export default router;