import { Router } from "express";
import * as categoryController from "./category.controller.js";
import fileUpload, { fileType } from './../../utls/multer.js';
import { auth } from '../../middelware/auth.js';
import subcategoryRouter from './../subcategory/subcategory.router.js';
import {endPoints} from '../category/category.role.js';
import { validation } from './../../middelware/validation.js';
import * as Schema  from '../category/category.validation.js';
const router = Router();
router.use('/:id/subcategory',subcategoryRouter);
router.post('/' ,auth(endPoints.create),fileUpload(fileType.image).single('image') ,validation(Schema.createCategoryCartSchema),categoryController.create);
router.get('/',auth(endPoints.get) ,categoryController.getAll);
router.get('/active' ,auth(endPoints.getActive) , categoryController.getActive);
router.get('/:id',validation(Schema.getDetailsSchema),auth(endPoints.getActive) ,categoryController.getDetails);
router.patch('/:id',fileUpload(fileType.image).single('image'),validation(Schema.updateSchema),auth(endPoints.create) ,categoryController.update);
router.delete('/:id',validation(Schema.deleteCategoryCartSchema),auth(endPoints.delete) ,categoryController.destory);
export default router; 